language: elixir
sudo: false
elixir:
  - '1.6'
otp_release:
  - '19.0'
after_success:
  - "mix compile && mix coveralls.travis"
after_script:
  - MIX_ENV=docs mix deps.get
  - MIX_ENV=docs mix inch.report
